### ISSUE TITLE
Update push.yml to java-version: "17.0"

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2679]
**Describe the bug**

In a recent PR, we upgraded packages that required an upgrade in the java version of the application. We updated our Pull Request testing workflow, but not the Push workflow that deploys the APK.

**To Reproduce**

1. https://github.com/PalisadoesFoundation/talawa/pull/2671/files

**Expected behavior**

- The push workflow file `push.yml` is updated to the new Java version and passes.
- This may only be testable after merging the related PR

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**

- N/A
**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by may-tas** [comment]
@palisadoes making a PR rn.

**Comment by palisadoes** [comment]
@may-tas 

What is causing this error? The pushes are failing in another way now:

- https://github.com/PalisadoesFoundation/talawa/actions/runs/12527917558/job/34941965288

**Comment by may-tas** [comment]
> @may-tas
> 
> What is causing this error? The pushes are failing in another way now:
> 
> * https://github.com/PalisadoesFoundation/talawa/actions/runs/12527917558/job/34941965288



> @may-tas
> 
> What is causing this error? The pushes are failing in another way now:
> 
> * https://github.com/PalisadoesFoundation/talawa/actions/runs/12527917558/job/34941965288

I'll take a look

**Comment by may-tas** [comment]
@palisadoes  The issue is that I did not include pubspec.lock file in the PR, and it changes whenever pub get is used.
So the workflow is doing pub get and the PR pubspec.lock branch is not matching with the updated pubspec.lock

See this is the issue while running pub get in workflow : 

<img width="613" alt="Screenshot 2024-12-28 at 9 46 19 PM" src="https://github.com/user-attachments/assets/779353fb-613c-46fb-b168-56d57b76f8c5" />

**Comment by may-tas** [comment]
@palisadoes I will make a PR updating pubspec.lock and that should fix this.

**Comment by palisadoes** [comment]
OK

**Comment by palisadoes** [comment]
How can we test for this in future as part of the GitHub action workflow?

**Comment by may-tas** [comment]
> How can we test for this in future as part of the GitHub action workflow?


We can do this in two ways : 

1. **First** (_Automated_) : 
- we can automate fixing it by running git add pubspec.lock && git commit -m "Update pubspec.lock" directly in the workflow if we want the workflow to handle minor issues itself.

2. **Second** : 
- We can add a check for it in the push.yml to verify that there are no uncommitted changes to the pubspec.lock file after running pub get. 
- This step should be added after the pub get command but before any further steps that depend on the resolved dependencies.
- The workflow will now fail if pubspec.lock is not committed after dependency changes, prompting contributors to fix it before merging.

**Comment by palisadoes** [comment]
Please add those steps

**Comment by may-tas** [comment]
which one ?

**Comment by may-tas** [comment]
Automated one? or 2nd

**Comment by palisadoes** [comment]
Automated.

**Comment by Dante291** [comment]
@may-tas it should work for both, yaml and lock files.

**Comment by may-tas** [comment]
Is this okay?

```
jobs:

  Flutter-Codebase-Check:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Checking Codebase
    runs-on: ubuntu-latest
    permissions:
      contents: write.       // Added this
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}     // Added this
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      - name: Running pub get in talawa_lint
        run: cd talawa_lint && flutter pub get && cd ..
      - name: Running pub get to fetch dependencies
        run: flutter pub get
      - name: Check and commit pubspec.lock changes   // Added this
        run: |
          if [[ `git status --porcelain pubspec.lock` ]]; then
            echo "Changes detected in pubspec.lock. Auto-committing updates."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add pubspec.lock
            git commit -m "Automated update of pubspec.lock"
            git push
          else
            echo "No changes in pubspec.lock."
          fi
      - name: Checking for correct formatting of code
        run: dart format --set-exit-if-changed .
       
        Rest is same

```
